/**
 * Copyright (c) 2012,USTC E-BUSINESS TECHNOLOGY CO.LTD All Rights Reserved.
 */
package com.sliu.framework.app.model;
// Generated 2015-2-12 14:01:02 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxSendallLog generated by hbm2java
 */
@Entity
@Table(name="WX_SENDALL_LOG"
)
public class WxSendallLog  implements java.io.Serializable {


     private Long logId;
     private Short isToAll;
     private Long groupId;
     private String mediaId;
     private String msgtype;
     private String title;
     private String description;
     private String thumbMediaId;
     private String sendUser;
     private Date sendTime;
     private String msgid;
     private String tousername;
     private String fromusername;
     private String status;
     private Integer totalcount;
     private Integer filtercount;
     private Integer sentcount;
     private Integer errorcount;

    public WxSendallLog() {
    }

	
    public WxSendallLog(Long logId) {
        this.logId = logId;
    }
    public WxSendallLog(Long logId, Short isToAll, Long groupId, String mediaId, String msgtype, String title, String description, String thumbMediaId, String sendUser, Date sendTime, String msgid, String tousername, String fromusername, String status, Integer totalcount, Integer filtercount, Integer sentcount, Integer errorcount) {
       this.logId = logId;
       this.isToAll = isToAll;
       this.groupId = groupId;
       this.mediaId = mediaId;
       this.msgtype = msgtype;
       this.title = title;
       this.description = description;
       this.thumbMediaId = thumbMediaId;
       this.sendUser = sendUser;
       this.sendTime = sendTime;
       this.msgid = msgid;
       this.tousername = tousername;
       this.fromusername = fromusername;
       this.status = status;
       this.totalcount = totalcount;
       this.filtercount = filtercount;
       this.sentcount = sentcount;
       this.errorcount = errorcount;
    }
   
    @Id 
 	@GeneratedValue(generator = "tableGenerator")     
    @GenericGenerator(name = "tableGenerator", strategy="com.sliu.framework.app.common.dao.key.SequenceGenerator")     
    @Column(name="LOG_ID", unique=true, nullable=false)
    public Long getLogId() {
        return this.logId;
    }
    
    public void setLogId(Long logId) {
        this.logId = logId;
    }
    
    @Column(name="IS_TO_ALL")
    public Short getIsToAll() {
        return this.isToAll;
    }
    
    public void setIsToAll(Short isToAll) {
        this.isToAll = isToAll;
    }
    
    @Column(name="GROUP_ID")
    public Long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }
    
    @Column(name="MEDIA_ID", length=100)
    public String getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }
    
    @Column(name="MSGTYPE", length=20)
    public String getMsgtype() {
        return this.msgtype;
    }
    
    public void setMsgtype(String msgtype) {
        this.msgtype = msgtype;
    }
    
    @Column(name="TITLE", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="THUMB_MEDIA_ID", length=100)
    public String getThumbMediaId() {
        return this.thumbMediaId;
    }
    
    public void setThumbMediaId(String thumbMediaId) {
        this.thumbMediaId = thumbMediaId;
    }
    
    @Column(name="SEND_USER")
    public String getSendUser() {
        return this.sendUser;
    }
    
    public void setSendUser(String sendUser) {
        this.sendUser = sendUser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SEND_TIME", length=26)
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
    
    @Column(name="MSGID", length=100)
    public String getMsgid() {
        return this.msgid;
    }
    
    public void setMsgid(String msgid) {
        this.msgid = msgid;
    }
    
    @Column(name="TOUSERNAME", length=100)
    public String getTousername() {
        return this.tousername;
    }
    
    public void setTousername(String tousername) {
        this.tousername = tousername;
    }
    
    @Column(name="FROMUSERNAME", length=100)
    public String getFromusername() {
        return this.fromusername;
    }
    
    public void setFromusername(String fromusername) {
        this.fromusername = fromusername;
    }
    
    @Column(name="STATUS", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="TOTALCOUNT")
    public Integer getTotalcount() {
        return this.totalcount;
    }
    
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }
    
    @Column(name="FILTERCOUNT")
    public Integer getFiltercount() {
        return this.filtercount;
    }
    
    public void setFiltercount(Integer filtercount) {
        this.filtercount = filtercount;
    }
    
    @Column(name="SENTCOUNT")
    public Integer getSentcount() {
        return this.sentcount;
    }
    
    public void setSentcount(Integer sentcount) {
        this.sentcount = sentcount;
    }
    
    @Column(name="ERRORCOUNT")
    public Integer getErrorcount() {
        return this.errorcount;
    }
    
    public void setErrorcount(Integer errorcount) {
        this.errorcount = errorcount;
    }




}
