/**
 * Copyright (c) 2012,USTC E-BUSINESS TECHNOLOGY CO.LTD All Rights Reserved.
 */
package com.sliu.framework.app.model;
// Generated 2014-12-9 14:25:46 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxSucaiInfo generated by hbm2java
 */
@Entity
@Table(name="WX_SUCAI_INFO"
)
public class WxSucaiInfo  implements java.io.Serializable {


     private Long scId;
     /*1:图片 2:语音 3:视频 4:图文消息*/
     private Integer scType;
     private Long attachmentId;
     private String scName;
     private String mediaId;
     private String remark;
     private String createUser;
     private Date createTime;

    public WxSucaiInfo() {
    }

	
    public WxSucaiInfo(Long scId) {
        this.scId = scId;
    }
    public WxSucaiInfo(Long scId, Integer scType, Long attachmentId, String scName, String mediaId, String remark, String createUser, Date createTime) {
       this.scId = scId;
       this.scType = scType;
       this.attachmentId = attachmentId;
       this.scName = scName;
       this.mediaId = mediaId;
       this.remark = remark;
       this.createUser = createUser;
       this.createTime = createTime;
    }
   
    @Id 
	@GeneratedValue(generator = "tableGenerator")     
    @GenericGenerator(name = "tableGenerator", strategy="com.sliu.framework.app.common.dao.key.SequenceGenerator")     
    @Column(name="SC_ID", unique=true, nullable=false)
    public Long getScId() {
        return this.scId;
    }
    
    public void setScId(Long scId) {
        this.scId = scId;
    }
    
    @Column(name="SC_TYPE")
    public Integer getScType() {
        return this.scType;
    }
    
    public void setScType(Integer scType) {
        this.scType = scType;
    }
    
    @Column(name="ATTACHMENT_ID")
    public Long getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }
    
    @Column(name="SC_NAME", length=100)
    public String getScName() {
        return this.scName;
    }
    
    public void setScName(String scName) {
        this.scName = scName;
    }
    
    @Column(name="MEDIA_ID", length=100)
    public String getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }
    
    @Column(name="REMARK", length=500)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="CREATE_USER", length=100)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=26)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}
