/**
 * Copyright (c) 2012,USTC E-BUSINESS TECHNOLOGY CO.LTD All Rights Reserved.
 */
package com.sliu.framework.app.model;
// Generated 2014-12-11 11:30:27 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxSucaiMpnews generated by hbm2java
 */
@Entity
@Table(name="WX_SUCAI_MPNEWS"
)
public class WxSucaiMpnews  implements java.io.Serializable {


     private Long mpnewsId;
     private Long scId;
     private String thumbMediaId;
     private String author;
     private String title;
     private String contentSourceUrl;
     private String mpContent;
     private String digest;
     private Integer showCoverPic;

    public WxSucaiMpnews() {
    }

	
    public WxSucaiMpnews(Long mpnewsId, Long scId) {
        this.mpnewsId = mpnewsId;
        this.scId = scId;
    }
    public WxSucaiMpnews(Long mpnewsId, Long scId, String thumbMediaId, String author, String title, String contentSourceUrl, String mpContent, String digest, Integer showCoverPic) {
       this.mpnewsId = mpnewsId;
       this.scId = scId;
       this.thumbMediaId = thumbMediaId;
       this.author = author;
       this.title = title;
       this.contentSourceUrl = contentSourceUrl;
       this.mpContent = mpContent;
       this.digest = digest;
       this.showCoverPic = showCoverPic;
    }
   
    @Id 
 	@GeneratedValue(generator = "tableGenerator")     
    @GenericGenerator(name = "tableGenerator", strategy="com.sliu.framework.app.common.dao.key.SequenceGenerator")   
    @Column(name="MPNEWS_ID", unique=true, nullable=false)
    public Long getMpnewsId() {
        return this.mpnewsId;
    }
    
    public void setMpnewsId(Long mpnewsId) {
        this.mpnewsId = mpnewsId;
    }
    
    @Column(name="SC_ID", nullable=false)
    public Long getScId() {
        return this.scId;
    }
    
    public void setScId(Long scId) {
        this.scId = scId;
    }
    
    @Column(name="THUMB_MEDIA_ID", length=100)
    public String getThumbMediaId() {
        return this.thumbMediaId;
    }
    
    public void setThumbMediaId(String thumbMediaId) {
        this.thumbMediaId = thumbMediaId;
    }
    
    @Column(name="AUTHOR", length=100)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    
    @Column(name="TITLE", length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="CONTENT_SOURCE_URL", length=100)
    public String getContentSourceUrl() {
        return this.contentSourceUrl;
    }
    
    public void setContentSourceUrl(String contentSourceUrl) {
        this.contentSourceUrl = contentSourceUrl;
    }
    
    @Column(name="MP_CONTENT", length=3000)
    public String getMpContent() {
        return this.mpContent;
    }
    
    public void setMpContent(String mpContent) {
        this.mpContent = mpContent;
    }
    
    @Column(name="DIGEST", length=100)
    public String getDigest() {
        return this.digest;
    }
    
    public void setDigest(String digest) {
        this.digest = digest;
    }
    
    @Column(name="SHOW_COVER_PIC", nullable=true)
    public Integer getShowCoverPic() {
        return this.showCoverPic;
    }
    
    public void setShowCoverPic(Integer showCoverPic) {
        this.showCoverPic = showCoverPic;
    }




}
