/**
 * Copyright (c) 2012,USTC E-BUSINESS TECHNOLOGY CO.LTD All Rights Reserved.
 */
package com.sliu.framework.app.model;
// Generated 2014-11-5 15:27:27 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxUserInfo generated by hbm2java
 */
@Entity
@Table(name="WX_USER_INFO"
)
public class WxUserInfo  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long userId;
     private Long groupId;
     private Integer subscribe;
     private String openid;
     private String nickname;
     private Integer sex;
     private String ULanguage;
     private String city;
     private String province;
     private String country;
     private String headimgurl;
     private String subscribeTime;
     private String unionid;
     private String remark;
     private String memo;

    public WxUserInfo() {
    }

	
    public WxUserInfo(Long userId) {
        this.userId = userId;
    }
    public WxUserInfo(Long userId, Long groupId, Integer subscribe, String openid, String nickname, Integer sex, String ULanguage, String city, String province, String country, String headimgurl, String subscribeTime, String unionid, String remark, String memo) {
       this.userId = userId;
       this.groupId = groupId;
       this.subscribe = subscribe;
       this.openid = openid;
       this.nickname = nickname;
       this.sex = sex;
       this.ULanguage = ULanguage;
       this.city = city;
       this.province = province;
       this.country = country;
       this.headimgurl = headimgurl;
       this.subscribeTime = subscribeTime;
       this.unionid = unionid;
       this.remark = remark;
       this.memo = memo;
    }
   
    @Id 
    @GeneratedValue(generator = "tableGenerator")     
    @GenericGenerator(name = "tableGenerator", strategy="com.sliu.framework.app.common.dao.key.SequenceGenerator")       
    @Column(name="USER_ID", unique=true, nullable=false)
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="GROUP_ID")
    public Long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }
    
    @Column(name="SUBSCRIBE")
    public Integer getSubscribe() {
        return this.subscribe;
    }
    
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }
    
    @Column(name="OPENID", length=100)
    public String getOpenid() {
        return this.openid;
    }
    
    public void setOpenid(String openid) {
        this.openid = openid;
    }
    
    @Column(name="NICKNAME", length=100)
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    
    @Column(name="SEX")
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }
    
    @Column(name="U_LANGUAGE", length=100)
    public String getULanguage() {
        return this.ULanguage;
    }
    
    public void setULanguage(String ULanguage) {
        this.ULanguage = ULanguage;
    }
    
    @Column(name="CITY", length=100)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="PROVINCE", length=100)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    
    @Column(name="COUNTRY", length=100)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="HEADIMGURL", length=200)
    public String getHeadimgurl() {
        return this.headimgurl;
    }
    
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }
    
    @Column(name="SUBSCRIBE_TIME", length=20)
    public String getSubscribeTime() {
        return this.subscribeTime;
    }
    
    public void setSubscribeTime(String subscribeTime) {
        this.subscribeTime = subscribeTime;
    }
    
    @Column(name="UNIONID", length=100)
    public String getUnionid() {
        return this.unionid;
    }
    
    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="MEMO", length=500)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }




}
