/**
 * Copyright (c) 2012,USTC E-BUSINESS TECHNOLOGY CO.LTD All Rights Reserved.
 */
package com.sliu.framework.app.model;
// Generated 2014-11-19 17:15:00 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxXdInfo generated by hbm2java
 */
@Entity
@Table(name="WX_XD_INFO"
)
public class WxXdInfo  implements java.io.Serializable {


     private Long xdId;
     private String openid;
     private String sqrxm;
     private String sqrsfz;
     private BigDecimal sqje;
     private String dkyt;
     private String lxfs;
     private Date sqsj;
     private Integer dealFlag;
     private String dealContent;

    public WxXdInfo() {
    }

	
    public WxXdInfo(Long xdId) {
        this.xdId = xdId;
    }
    public WxXdInfo(Long xdId, String openid, String sqrxm, String sqrsfz, BigDecimal sqje, String dkyt, String lxfs, Date sqsj, Integer dealFlag, String dealContent) {
       this.xdId = xdId;
       this.openid = openid;
       this.sqrxm = sqrxm;
       this.sqrsfz = sqrsfz;
       this.sqje = sqje;
       this.dkyt = dkyt;
       this.lxfs = lxfs;
       this.sqsj = sqsj;
       this.dealFlag = dealFlag;
       this.dealContent = dealContent;
    }
   
    @Id 
    @GeneratedValue(generator = "tableGenerator")     
    @GenericGenerator(name = "tableGenerator", strategy="com.sliu.framework.app.common.dao.key.SequenceGenerator")    
    @Column(name="XD_ID", unique=true, nullable=false)
    public Long getXdId() {
        return this.xdId;
    }
    
    public void setXdId(Long xdId) {
        this.xdId = xdId;
    }
    
    @Column(name="OPENID", length=100)
    public String getOpenid() {
        return this.openid;
    }
    
    public void setOpenid(String openid) {
        this.openid = openid;
    }
    
    @Column(name="SQRXM", length=100)
    public String getSqrxm() {
        return this.sqrxm;
    }
    
    public void setSqrxm(String sqrxm) {
        this.sqrxm = sqrxm;
    }
    
    @Column(name="SQRSFZ", length=50)
    public String getSqrsfz() {
        return this.sqrsfz;
    }
    
    public void setSqrsfz(String sqrsfz) {
        this.sqrsfz = sqrsfz;
    }
    
    @Column(name="SQJE", precision=15)
    public BigDecimal getSqje() {
        return this.sqje;
    }
    
    public void setSqje(BigDecimal sqje) {
        this.sqje = sqje;
    }
    
    @Column(name="DKYT", length=500)
    public String getDkyt() {
        return this.dkyt;
    }
    
    public void setDkyt(String dkyt) {
        this.dkyt = dkyt;
    }
    
    @Column(name="LXFS", length=50)
    public String getLxfs() {
        return this.lxfs;
    }
    
    public void setLxfs(String lxfs) {
        this.lxfs = lxfs;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SQSJ", length=26)
    public Date getSqsj() {
        return this.sqsj;
    }
    
    public void setSqsj(Date sqsj) {
        this.sqsj = sqsj;
    }
    
    @Column(name="DEAL_FLAG")
    public Integer getDealFlag() {
        return this.dealFlag;
    }
    
    public void setDealFlag(Integer dealFlag) {
        this.dealFlag = dealFlag;
    }
    
    @Column(name="DEAL_CONTENT", length=500)
    public String getDealContent() {
        return this.dealContent;
    }
    
    public void setDealContent(String dealContent) {
        this.dealContent = dealContent;
    }




}
